# tasks file for zend-opcache-dashboards
---
- name: create (download) directory
  file:
    path: "{{ zend_opcache_dashboards_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, zend-opcache-dashboards, zend-opcache-dashboards-download]

- name: download (latest)
  get_url:
    url: "{{ item.url }}"
    dest: "{{ zend_opcache_dashboards_download_path }}/{{ item.name }}.php"
    owner: root
    group: root
    mode: 0644
    force: true
  with_items: zend_opcache_dashboards_install_map
  tags: [configuration, zend-opcache-dashboards, zend-opcache-dashboards-download]

- name: install
  file:
    src: "{{ zend_opcache_dashboards_download_path }}/{{ item.0.name }}.php"
    dest: "{{ item.1 }}/{{ item.0.name }}.php"
    state: link
    force: true
  with_nested:
    - zend_opcache_dashboards_install_map
    - zend_opcache_dashboards_install_dirs
  tags: [configuration, zend-opcache-dashboards, zend-opcache-dashboards-install]
